[package]
name = "anagma"
version = "0.1.0"
authors = ["Mark LeMoine <linclelinkpart5@gmail.com>"]
edition = "2018"
description = "A new standard for storing hierarchical metadata for data/media files in external configuration files."
license = "MIT"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
globset = "0.4"
rust_decimal = { version = "1.0", features = ["serde"] }
rust_decimal_macros = "1.0"
strum = "0.16"
strum_macros = "0.16"
indexmap = { version = "1.2", features = ["serde-1"] }

[dev-dependencies]
maplit = "1"
tempfile = "3"
rand = "*"
matches = "*"
