[package]
name = "taggu"
version = "0.1.0"
authors = ["Mark LeMoine <thatsgobbles@gmail.com>"]

[dependencies]
failure = "0.1.2"
regex = "1.0.2"
maplit = "1.0.1"
yaml-rust = "0.4.0"
serde = "1.0.73"
serde_yaml = "0.8.1"
serde_derive = "1.0"
serde_regex = "0.3.0"
globset = "0.4.1"

[dev-dependencies]
tempdir = "0.3.7"
