[package]
name = "taggu"
version = "0.1.0"
authors = ["Mark LeMoine <thatsgobbles@gmail.com>"]

[dependencies]
failure = "0.1.2"
regex = "1.0.2"
maplit = "1.0.1"

[dev-dependencies]
tempdir = "0.3.7"
