[package]
name = "anagma"
version = "0.1.0"
authors = ["Mark LeMoine <thatsgobbles@gmail.com>"]

[dependencies]
maplit = "1.0.1"
serde = "1.0.73"
serde_yaml = "^0.8"
serde_derive = "1.0"
globset = "0.4.1"
log = "0.4"
itertools = "0.7.3"
serde_json = "1.0"

[dev-dependencies]
tempfile = "3"
